// <auto-generated />
using ComparaItens.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComparaItens.Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("ComparaItens.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("tabCategory");
                });

            modelBuilder.Entity("ComparaItens.Domain.Entities.Characteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int(11)")
                        .HasColumnName("categoryId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Id");

                    b.ToTable("tabCharacteristic");
                });

            modelBuilder.Entity("ComparaItens.Domain.Entities.CharacteristicDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int>("CharacteristicId")
                        .HasColumnType("int(11)")
                        .HasColumnName("characteristicId");

                    b.Property<int>("CharacteristicKeyId")
                        .HasColumnType("int(11)")
                        .HasColumnName("characteristicKeyId");

                    b.Property<int>("ProductId")
                        .HasColumnType("int(11)")
                        .HasColumnName("productId");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("CharacteristicKeyId");

                    b.HasIndex("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("tabCharacteristicDescription");
                });

            modelBuilder.Entity("ComparaItens.Domain.Entities.CharacteristicKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int>("CharacteristicId")
                        .HasColumnType("int(11)")
                        .HasColumnName("characteristicId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("Id");

                    b.ToTable("tabCharacteristicKey");
                });

            modelBuilder.Entity("ComparaItens.Domain.Entities.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("tabManufacturer");
                });

            modelBuilder.Entity("ComparaItens.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int(11)")
                        .HasColumnName("categoryId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int(11)")
                        .HasColumnName("manufacturerId");

                    b.Property<string>("Model")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("model");

                    b.Property<int>("YearOfManufacture")
                        .HasColumnType("int(11)")
                        .HasColumnName("yearOfManufacture");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("tabProdut");
                });

            modelBuilder.Entity("ComparaItens.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("tabUser");
                });

            modelBuilder.Entity("ComparaItens.Domain.Entities.Characteristic", b =>
                {
                    b.HasOne("ComparaItens.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ComparaItens.Domain.Entities.CharacteristicDescription", b =>
                {
                    b.HasOne("ComparaItens.Domain.Entities.Characteristic", "Characteristics")
                        .WithMany()
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComparaItens.Domain.Entities.CharacteristicKey", "CharacteristicKeys")
                        .WithMany()
                        .HasForeignKey("CharacteristicKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacteristicKeys");

                    b.Navigation("Characteristics");
                });

            modelBuilder.Entity("ComparaItens.Domain.Entities.CharacteristicKey", b =>
                {
                    b.HasOne("ComparaItens.Domain.Entities.Characteristic", "Characteristics")
                        .WithMany()
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Characteristics");
                });

            modelBuilder.Entity("ComparaItens.Domain.Entities.Product", b =>
                {
                    b.HasOne("ComparaItens.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComparaItens.Domain.Entities.Manufacturer", "Manufecturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Manufecturer");
                });
#pragma warning restore 612, 618
        }
    }
}
